### ISSUE TITLE
taking ms-like input for summary stats computation?

### ISSUE THREAD

**Issue by hsiehph** [molpopgen/pyseq#15] opened 2019-03-04 00:46 UTC
Hi,

I would like to use pylibseq to take ms-like input (file or file object) and compute summary statistics.
The function, libsequence.variant_matrix.ms_from_stdin, seems the right one for this purpose, but I cannot find any detail description on how it is supposed to work. Would you mind of giving a short example for this purpose and then compute some summary statistics? I know the interfaces to msprime is better supported, but at this moment my pipeline still heavy depends on ms and its kind. Switching everything to msprime will take me some time to reconstruct and evaluate consistency.

Thanks,
Benson

**Comment by molpopgen** [comment] 2019-03-04 01:02
You simply call the function, which is a member of the module:

```py
import libsequence.variant_matrix as vmtrx

vm = vmtrx.ms_from_stdin()
```

It returns `None` if stdin is at eof, otherwise it returns a `VariantMatrix`.  After that, everything is normal as far as summary stats are concerned.

**Comment by hsiehph** [comment] 2019-03-04 04:16
Thanks for the quick response.

Is this ms_from_stdin equivalent to sys.stdin?
Is there an easy way to for libsequence to read ms-like input from a
subprocess.Popen object? I would like to put ms simulation and compute
summary statistics in a single python script. I tried a few ways, but the
function does not take any argument.

Thanks!

**Comment by molpopgen** [comment] 2019-03-04 04:32
Yes, it is intended to be used via a Unix pipe, and not via a Process:

ms | script.py

**Comment by hsiehph** [comment] 2019-03-04 04:40
ah..... That makes sense now. hmm... That is a bit unfortunate for me as I
was hoping to have everything running within the script.

Thanks!

**Comment by molpopgen** [comment] 2019-03-04 04:47
Take a look at the sh module.  It allows call backs, but not sure if this
function will work

**Comment by molpopgen** [comment] 2019-03-04 04:54
An alternative is to write your own code to convert input into two numpy
array and construct the variant matrix directly.  The parsing of the ms
format is easy.

**Comment by hsiehph** [comment] 2019-03-04 04:56
Thanks. I will give the sh module a try.

**Comment by agladstein** [comment] 2019-03-04 18:12
@hsiehph fyi, msprime can output np array directly.
https://tskit.readthedocs.io/en/stable/python-api.html#tskit.TreeSequence.genotype_matrix

**Comment by molpopgen** [comment] 2019-03-04 18:22
> @hsiehph fyi, msprime can output np array directly.
> https://tskit.readthedocs.io/en/stable/python-api.html#tskit.TreeSequence.genotype_matrix

The OP doesn't want to use msprime.

I am closing this now, as the issue is resolved.

**Closed as completed by molpopgen** 2019-03-04 18:22 UTC

**Comment by hsiehph** [comment] 2019-03-04 18:32
Thanks, Ariella (btw, good to hear from you!). Kevin is right about my
intent as my pipeline still depends on the old fashion ms-like simulations.
I am gradually (very slowly) switch to msprime if applicable, but it is a
sort of a painful process. :p

**Comment by agladstein** [comment] 2019-03-04 18:35
@hsiehph I see...
You have you to just rip off the bandaid! haha
